### PR TITLE
Forpr

### PR DESCRIPTION
**Pull request by montjoie**

### CODE REVIEW

**Comment by lucj** [comment]
Thanks @montjoie for those changes.
Could you just keep the version '3' of the Docker Compose file ?

**Comment by lucj** [comment]
On the first run of the application, the download of the images can take quite some time (I'll add an issue to shrink them a little bit). I'm afraid a 60sec timeout might be too short in some cases.
Could you increase it and add something like "please be patient, image download can take a couple of minutes on the first run" ?
What do you think ?

**Comment by montjoie** [comment]
Ok I will update timeout to more (240 ? 300?)
For the version we should keep the lower that works

**Comment by lucj** [comment]
I think 120 should be fine, we'll adjust the value later on.
Regarding the version used in the Docker Compose, I'd rather use a newer version of the Docker daemon (one that supports the latest version, and which also fix bugs at the same time).
If you use 17.06+, the version 3 should not be a problem (https://github.com/docker/compose/releases). Do you confirm ?

**Comment by montjoie** [comment]
I use a debian 9.

**Pull request merged**
